#!/bin/bash

# This script runs a Python script inside a Docker container.
# It accepts the script file as the first argument and any additional command line arguments after that.

if [ -z "$1" ]; then
    echo "Usage: $0 your_script.py [args...]"
    exit 1
fi

ARGUMENT=$1

# Run the Docker container with the specified Python script and pass any additional arguments to it.
docker run --rm -v $(pwd):/app python_3_13_nogil:latest python3 $ARGUMENT "${@:2}"